name: Test Self-Hosted Runner

on:
  workflow_dispatch:   # manual trigger

jobs:
  test:
    runs-on: arc-runner-set

    steps:
      - name: Print Hello
        run: echo "Hello from Kubernetes Runner 🚀"

      - name: Show System Info
        run: |
          uname -a
          whoami
          pwd

      - name: Sleep (to observe pod)
        run: sleep 60
